spring:
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL

  h2:
    console:
      enabled: true

server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true

